
 [[https://mybinder.org/v2/gh/leandroohf/LDA.git/master][https://mybinder.org/badge_logo.svg]]

 These are my notes and implementations of some machine learning algorithms.

* Intro to Gradient Descent

  See notebook: [[intro_gradient_algos.ipynb]]

* Intro to GANS

 See notebook: [[intro_gans.ipynb]]

* Intro to KNN

  See notebook: [[intro_KNN.ipynb]]

* Intro to K-means

  TODO:
  
* Intro to GMM and EM algorithm
  
  Please, visit notebook:  [[file:intro_gmm_n_em.ipynb][Gaussian Mixture Models]]

  refs:
  1. https://github.com/llSourcell/Gaussian_Mixture_Models
  2. https://github.com/brianspiering/gaussian_mixture_models
  3. https://jakevdp.github.io/PythonDataScienceHandbook/05.12-gaussian-mixtures.html
  4. https://github.com/jakevdp/PythonDataScienceHandbook
     
  See video: 
  1. https://www.youtube.com/watch?v=JNlEIEwe-Cg

* Intro Calibration curve
  
  The score you get from a binary classifier (that outputs a number between 0
  and 1.0 is not necessarily a well-calibrated probability. Even some models
  that provide a method that return the predicted probability can give you poor
  estimates of the class probabilities. The tools utilized to calibrate a model
  are sometimes called calibration curve (Python) or reliability diagrams (R).

  See:
    
  [[file:intro_calibration_curve.ipynb]]

** refs

   https://scikit-learn.org/stable/auto_examples/calibration/plot_calibration.html

   http://queirozf.com/entries/introduction-to-auc-and-calibrated-models-with-examples-using-scikit-learn
   
   https://machinelearningmastery.com/calibrated-classification-model-in-scikit-learn/

   http://danielnee.com/tag/reliability-diagram/

* Intro to Fishers LDA

  See notebook: [[file:intro_fishers_lda.ipynb][Fisher LDA]]

* Intro to LDA and QDA

  See notebook: [[file:intro_lda.ipynb][LDA/QDA]]

* Intro to PCA

  See notebook: [[file:intro_pca.ipynb][PCA]]

* Intro to PLDA
  
  See the notebook: [[file:intro_plda.ipynb][PLDA]]
  
* Intro to t_SNE

  *TODO*

* Intro to LSTM Unit (Deep Learning Architecture)

  See [[file:intro_lstm_unit.ipynb][LSTM]]

* Notes about learning curve and deep learning

  See [[file:deep_learning_notes.ipynb][Deep Learning]]
